-- -----------------------------------------------------
-- Table SIF3_JOB_TEMPLATE
-- -----------------------------------------------------
CREATE TABLE SIF3_JOB_TEMPLATE (
  JOB_TEMPLATE_ID INT NOT NULL,
  JOB_URL_NAME VARCHAR2(100) NOT NULL,
  ADAPTER_TYPE VARCHAR2(20) NULL,
  TEMPLATE_FILE_NAME VARCHAR2(100) NOT NULL,
  PRIMARY KEY (JOB_TEMPLATE_ID));

CREATE UNIQUE INDEX UQ_JOB_URL_NAME ON SIF3_JOB_TEMPLATE (JOB_URL_NAME ASC, ADAPTER_TYPE ASC);

-- -----------------------------------------------------
-- Table SIF3_JOB
-- -----------------------------------------------------
CREATE TABLE SIF3_JOB (
  JOB_ID INT NOT NULL,
  JOB_REFID VARCHAR2(36) NOT NULL,
  SERVICE_NAME VARCHAR2(256) NULL,
  CURRENT_JOB_STATE VARCHAR2(30) NULL,
  ENVIRONMENT_REFID VARCHAR2(36) NULL,
  ADAPTER_TYPE VARCHAR2(20) NOT NULL,
  FINGERPRINT VARCHAR2(256) NULL,
  ZONE_ID VARCHAR2(256) NULL,
  CONTEXT_ID VARCHAR2(255) NULL,
  CREATED TIMESTAMP NOT NULL,
  TIMEOUT_PERIOD VARCHAR2(30) NULL,
  LAST_MODIFIED TIMESTAMP NULL,
  EXPIRE_DATETIME TIMESTAMP NULL,
  JOB_XML CLOB NULL,
  PRIMARY KEY (JOB_ID));

CREATE INDEX JOB_JOBREFID_ADPTYPE_IDX ON SIF3_JOB (JOB_REFID ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOB_FINGERPRT_ADPTYPE_IDX ON SIF3_JOB (FINGERPRINT ASC, SERVICE_NAME ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOB_ENVREFID_ADPTYPE_IDX ON SIF3_JOB (FINGERPRINT ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOB_ZONEID_ADPTYPE_IDX ON SIF3_JOB (ZONE_ID ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOB_REFID_ENVREFID_ADPTYPE_IDX ON SIF3_JOB (JOB_REFID ASC, ENVIRONMENT_REFID ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOB_SVCNNAME_ADPTYPE_IDX ON SIF3_JOB (SERVICE_NAME ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOB_EXPIRE_IDX ON SIF3_JOB (EXPIRE_DATETIME ASC);

-- -----------------------------------------------------
-- Table SIF3_JOB_EVENT
-- -----------------------------------------------------
CREATE TABLE SIF3_JOB_EVENT (
  JOB_EVENT_ID INT NOT NULL,
  JOB_EVENT_DATETIME TIMESTAMP NOT NULL,
  JOB_REFID VARCHAR2(36) NOT NULL,
  SERVICE_NAME VARCHAR2(256) NULL,
  ENVIRONMENT_REFID VARCHAR2(36) NULL,
  ADAPTER_TYPE VARCHAR2(20) NOT NULL,
  FINGERPRINT VARCHAR2(256) NULL,
  ZONE_ID VARCHAR2(256) NULL,
  CONTEXT_ID VARCHAR2(256) NULL,
  EVENT_TYPE CHAR NOT NULL,
  FULL_UPDATE CHAR DEFAULT 'Y' NOT NULL,
  TO_FINGERPRINT_ONLY CHAR DEFAULT 'Y' NOT NULL,
  EVENT_PUBLISHED CHAR DEFAULT 'N' NOT NULL,
  PUBLISHED_DATETIME TIMESTAMP NULL,
  JOB_XML CLOB NULL,
  PRIMARY KEY (JOB_EVENT_ID));

CREATE INDEX JOBEVT_DT_ADPTY_IDX ON SIF3_JOB_EVENT (JOB_EVENT_DATETIME ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOBEVT_JOBREFID_ADPTY_IDX ON SIF3_JOB_EVENT (JOB_REFID ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOBEVT_FINGERPRT_ADPTY_IDX ON SIF3_JOB_EVENT (FINGERPRINT ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOBEVT_ENVREFID_ADPTY_IDX ON SIF3_JOB_EVENT (ENVIRONMENT_REFID ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOBEVT_ZONEID_ADPTY_IDX ON SIF3_JOB_EVENT (ZONE_ID ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOBEVT_DT_EVTY_ADPTY_PUBL_IDX ON SIF3_JOB_EVENT (JOB_EVENT_DATETIME ASC, ADAPTER_TYPE ASC, EVENT_TYPE ASC, EVENT_PUBLISHED ASC);

CREATE INDEX JOBEVT_DT__ADPTY_PUBL_IDX ON SIF3_JOB_EVENT (JOB_EVENT_DATETIME ASC, ADAPTER_TYPE ASC, EVENT_PUBLISHED ASC);

CREATE INDEX JOBEVT_JOBID_ENVID_ADPTY_IDX ON SIF3_JOB_EVENT (JOB_REFID ASC, ENVIRONMENT_REFID ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOBEVT_SVCNAME_ADPTYPE_IDX ON SIF3_JOB_EVENT (SERVICE_NAME ASC, ADAPTER_TYPE ASC);

