-- -----------------------------------------------------
-- Table SIF3_JOB_TEMPLATE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS SIF3_JOB_TEMPLATE (
  JOB_TEMPLATE_ID INT NOT NULL,
  JOB_URL_NAME VARCHAR(100) NOT NULL,
  ADAPTER_TYPE VARCHAR(20) NULL,
  TEMPLATE_FILE_NAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (JOB_TEMPLATE_ID));

CREATE UNIQUE INDEX UQ_JOB_URL_NAME ON SIF3_JOB_TEMPLATE (JOB_URL_NAME ASC, ADAPTER_TYPE ASC);

-- -----------------------------------------------------
-- Table SIF3_JOB
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS SIF3_JOB (
  JOB_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  JOB_REFID VARCHAR(36) NOT NULL,
  SERVICE_NAME VARCHAR(256) NULL,
  CURRENT_JOB_STATE VARCHAR(30) NULL,
  ENVIRONMENT_REFID VARCHAR(36) NULL,
  ADAPTER_TYPE VARCHAR(20) NOT NULL,
  FINGERPRINT VARCHAR(256) NULL,
  ZONE_ID VARCHAR(256) NULL,
  CONTEXT_ID VARCHAR(255) NULL,
  CREATED DATETIME NOT NULL,
  TIMEOUT_PERIOD VARCHAR(30) NULL,
  LAST_MODIFIED DATETIME NULL,
  EXPIRE_DATETIME DATETIME NULL,
  JOB_XML TEXT NULL);

CREATE INDEX JOB_JOBREFID_ADPTYPE_IDX ON SIF3_JOB (JOB_REFID ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOB_FINGERPRT_ADPTYPE_IDX ON SIF3_JOB (FINGERPRINT ASC, SERVICE_NAME ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOB_ENVREFID_ADPTYPE_IDX ON SIF3_JOB (FINGERPRINT ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOB_ZONEID_ADPTYPE_IDX ON SIF3_JOB (ZONE_ID ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOB_REFID_ENVREFID_ADPTYPE_IDX ON SIF3_JOB (JOB_REFID ASC, ENVIRONMENT_REFID ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOB_SVCNNAME_ADPTYPE_IDX ON SIF3_JOB (SERVICE_NAME ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOB_EXPIRE_IDX ON SIF3_JOB (EXPIRE_DATETIME ASC);

-- -----------------------------------------------------
-- Table SIF3_JOB_EVENT
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS SIF3_JOB_EVENT (
  JOB_EVENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  JOB_EVENT_DATETIME DATETIME NOT NULL,
  JOB_REFID VARCHAR(36) NOT NULL,
  SERVICE_NAME VARCHAR(256) NULL,
  ENVIRONMENT_REFID VARCHAR(36) NULL,
  ADAPTER_TYPE VARCHAR(20) NOT NULL,
  FINGERPRINT VARCHAR(256) NULL,
  ZONE_ID VARCHAR(256) NULL,
  CONTEXT_ID VARCHAR(256) NULL,
  EVENT_TYPE CHAR(1) NOT NULL,
  FULL_UPDATE INTEGER NOT NULL DEFAULT 1,
  TO_FINGERPRINT_ONLY INTEGER NOT NULL DEFAULT 1,
  CONSUMER_REQUESTED INTEGER NOT NULL DEFAULT 1,
  EVENT_PUBLISHED INTEGER NOT NULL DEFAULT 0,
  PUBLISHED_DATETIME DATETIME NULL,
  JOB_XML TEXT NULL);

CREATE INDEX JOBEVT_DT_ADPTY_IDX ON SIF3_JOB_EVENT (JOB_EVENT_DATETIME ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOBEVT_JOBREFID_ADPTY_IDX ON SIF3_JOB_EVENT (JOB_REFID ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOBEVT_FINGERPRT_ADPTY_IDX ON SIF3_JOB_EVENT (FINGERPRINT ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOBEVT_ENVREFID_ADPTY_IDX ON SIF3_JOB_EVENT (ENVIRONMENT_REFID ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOBEVT_ZONEID_ADPTY_IDX ON SIF3_JOB_EVENT (ZONE_ID ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOBEVT_DT_EVTY_ADPTY_PUBL_IDX ON SIF3_JOB_EVENT (JOB_EVENT_DATETIME ASC, ADAPTER_TYPE ASC, EVENT_TYPE ASC, EVENT_PUBLISHED ASC);

CREATE INDEX JOBEVT_DT__ADPTY_PUBL_IDX ON SIF3_JOB_EVENT (JOB_EVENT_DATETIME ASC, ADAPTER_TYPE ASC, EVENT_PUBLISHED ASC);

CREATE INDEX JOBEVT_JOBID_ENVID_ADPTY_IDX ON SIF3_JOB_EVENT (JOB_REFID ASC, ENVIRONMENT_REFID ASC, ADAPTER_TYPE ASC);

CREATE INDEX JOBEVT_SVCNAME_ADPTYPE_IDX ON SIF3_JOB_EVENT (SERVICE_NAME ASC, ADAPTER_TYPE ASC);

