-- -----------------------------------------------------
-- Table SIF3_EXT_SECURITY_SERVICE
-- -----------------------------------------------------
CREATE TABLE SIF3_EXT_SECURITY_SERVICE (
  EXT_SECURITY_SERVICE_ID INT NOT NULL,
  AUTH_METHOD VARCHAR2(20) NULL,
  ADAPTER_TYPE VARCHAR2(20) NULL,
  HTTP_HEADER_VALUE VARCHAR2(20) NULL,
  XML_VALUE VARCHAR2(20) NULL,
  TWO_PHASE CHAR  DEFAULT 'N' NOT NULL,
  IMPLEMENTATION_CLASS VARCHAR2(256) NULL,
  PRIMARY KEY (EXT_SECURITY_SERVICE_ID));

CREATE UNIQUE INDEX UQ_AUTH_METH_ADAP ON SIF3_EXT_SECURITY_SERVICE (AUTH_METHOD ASC, ADAPTER_TYPE ASC);

-- -----------------------------------------------------
-- Table SIF3_SEC_SERVICE_PARAM
-- -----------------------------------------------------
CREATE TABLE SIF3_SEC_SERVICE_PARAM (
  SEC_SERVICE_PARAM_ID INT NOT NULL,
  EXT_SECURITY_SERVICE_ID INT NOT NULL,
  PARAM_NAME VARCHAR2(45) NULL,
  PARAM_VALUE VARCHAR2(256) NULL,
  PRIMARY KEY (SEC_SERVICE_PARAM_ID));

ALTER TABLE SIF3_SEC_SERVICE_PARAM 
ADD CONSTRAINT FK_SEC_SVC_PARAM_TO_SEC_SVC 
FOREIGN KEY (EXT_SECURITY_SERVICE_ID)    
REFERENCES SIF3_EXT_SECURITY_SERVICE (EXT_SECURITY_SERVICE_ID);

CREATE INDEX IDX_EXT_SEC_SVC ON SIF3_SEC_SERVICE_PARAM (EXT_SECURITY_SERVICE_ID ASC);
