-- -----------------------------------------------------
-- Table SIF3_EXT_SECURITY_SERVICE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS SIF3_EXT_SECURITY_SERVICE (
  EXT_SECURITY_SERVICE_ID INTEGER NOT NULL,
  AUTH_METHOD VARCHAR(20) NULL,
  ADAPTER_TYPE VARCHAR(20) NULL,
  HTTP_HEADER_VALUE VARCHAR(20) NULL,
  XML_VALUE VARCHAR(20) NULL,
  TWO_PHASE INTEGER NOT NULL DEFAULT 0,
  IMPLEMENTATION_CLASS VARCHAR(256) NULL,
  PRIMARY KEY (EXT_SECURITY_SERVICE_ID));

CREATE UNIQUE INDEX UQ_AUTH_METH_ADAP ON SIF3_EXT_SECURITY_SERVICE (AUTH_METHOD ASC, ADAPTER_TYPE ASC);

-- -----------------------------------------------------
-- Table SIF3_SEC_SERVICE_PARAM
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS SIF3_SEC_SERVICE_PARAM (
  SEC_SERVICE_PARAM_ID INTEGER NOT NULL,
  EXT_SECURITY_SERVICE_ID INTEGER NOT NULL,
  PARAM_NAME VARCHAR(45) NULL,
  PARAM_VALUE VARCHAR(256) NULL,
  PRIMARY KEY (SEC_SERVICE_PARAM_ID),
  CONSTRAINT FK_SEC_SVC_PARAM_TO_SEC_SVC
    FOREIGN KEY (EXT_SECURITY_SERVICE_ID)
    REFERENCES SIF3_EXT_SECURITY_SERVICE (EXT_SECURITY_SERVICE_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX IDX_EXT_SEC_SVC ON SIF3_SEC_SERVICE_PARAM (EXT_SECURITY_SERVICE_ID ASC);
