ALTER TABLE SIF3_SESSION ADD (SECURITY_TOKEN VARCHAR2(200) NULL,
                              SECURITY_TOKEN_EXPIRY TIMESTAMP NULL);

CREATE INDEX SEC_TOKEN_IDX ON SIF3_SESSION (SECURITY_TOKEN ASC, ADAPTER_TYPE ASC);
