/*
 * EventInfo.java Created: 09/05/2014
 * 
 * Copyright 2014 Systemic Pty Ltd
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package sif3.infra.rest.queue.types;

import java.io.Serializable;

import javax.ws.rs.core.MediaType;

import sif3.common.header.HeaderValues.EventAction;
import sif3.common.header.HeaderValues.MessageType;
import sif3.common.header.HeaderValues.ServiceType;
import sif3.common.header.HeaderValues.UpdateType;
import sif3.common.model.EventMetadata;
import sif3.common.model.SIFContext;
import sif3.common.model.SIFZone;

/**
 * This class is a utility type to allow event consumer package the actual event data and related
 * information in one structure. This type uses the actual event data as a String as it has been
 * received from the remote message queue. This is so that the event is still raw without the need
 * of knowing what to unmarshal it into until it is actually send to the final event consumer. This
 * way an event can easily be passed between classes and processed without having the need of many
 * parameters or actual knowledge of the event object class<br/>
 * <br/>
 * 
 * @author Joerg Huber
 *
 */
public class EventInfo extends QueueMessage implements Serializable
{
    private static final long serialVersionUID = -920081412771061609L;

    // Actual Event data
    private EventAction eventAction;
    private UpdateType updateType;
    
    // metadata of event generated by provider of event 
    private EventMetadata eventMetadata;           

    public EventInfo()
    {
        this(null, null, null, null, null, null, null, null);
    }

    public EventInfo(String payload, MediaType mediaType)
    {
        this(payload, mediaType, null, null, null, null, null, null);
    }

    public EventInfo(String payload, MediaType mediaType, EventAction eventAction)
    {
        this(payload, mediaType, eventAction, null, null, null, null, null);
    }

    public EventInfo(String payload, MediaType mediaType, EventAction eventAction,
            UpdateType updateType)
    {
        this(payload, mediaType, eventAction, updateType, null, null, null, null);
    }

    public EventInfo(String payload, MediaType mediaType, EventAction eventAction,
            UpdateType updateType, SIFZone zone, SIFContext context)
    {
        this(payload, mediaType, eventAction, updateType, zone, context, null, null);
    }

    public EventInfo(String payload, MediaType mediaType, EventAction eventAction, UpdateType updateType, SIFZone zone, SIFContext context, EventMetadata eventMetadata)
    {
        this(payload, mediaType, eventAction, updateType, zone, context, eventMetadata, null);
    }

    public EventInfo(String payload, MediaType mediaType, EventAction eventAction, UpdateType updateType, SIFZone zone, SIFContext context, EventMetadata eventMetadata, String messageQueueReaderID)
    {
        super(payload, mediaType, ServiceType.OBJECT, MessageType.EVENT, zone, context, messageQueueReaderID);
        setEventAction(eventAction);
        setUpdateType(updateType);
        setEventMetadata(eventMetadata);
    }

    public EventAction getEventAction()
    {
        return eventAction;
    }

    public void setEventAction(EventAction eventAction)
    {
        this.eventAction = eventAction;
    }

    public UpdateType getUpdateType()
    {
        return updateType;
    }

    public void setUpdateType(UpdateType updateType)
    {
        this.updateType = updateType;
    }

    public EventMetadata getEventMetadata()
    {
        return this.eventMetadata;
    }

    public void setEventMetadata(EventMetadata eventMetadata)
    {
        this.eventMetadata = eventMetadata;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString()
    {
        return "EventInfo [eventAction=" + eventAction + ", updateType=" + updateType
                + ", eventMetadata=" + eventMetadata + ", toString()=" + super.toString() + "]";
    }
}
